apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.1.53.38/32
    cni.projectcalico.org/podIPs: 10.1.53.38/32
  creationTimestamp: "2021-11-19T02:55:21Z"
  labels:
    crowdstrike.com/component: crowdstrike-falcon-sensor
    crowdstrike.com/provider: crowdstrike
    run: busy-hello
  name: busy-hello
  namespace: falconlab
  resourceVersion: "103878"
  selfLink: /api/v1/namespaces/falconlab/pods/busy-hello
  uid: 02dfb657-c4ad-481b-a0a3-1af5c4edde89
spec:
  containers:
  - env:
    - name: __CS_POD_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: __CS_POD_IP4
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: __CS_POD_HOST_IP4
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: __CS_POD_SERVICE_ACCOUNT_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: __CS_POD_HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: __CS_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: __CS_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: __CS_POD_SPEC
      value: '{"containers":[{"command":["/bin/sh","-c","while true;do echo ''hello
        there from pod'';sleep 300;done"],"image":"busybox","imageDigest":"e7157b6d7ebbe2cce5eaa8cfe8aa4fa82d173999b9f90a9ec42e57323546c353","imageID":"7138284460ffa3bb6ee087344f5b051468b3f8697e2d1427bac1a20c8d168b14","imagePullPolicy":"Always","imageSchemaVersion":2,"name":"busy-hello","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"kube-api-access-987l6","readOnly":true}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-987l6","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"items":[{"key":"ca.crt","path":"ca.crt"}],"name":"kube-root-ca.crt"}},{"downwardAPI":{"items":[{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"},"path":"namespace"}]}}]}}]}'
    - name: __CS_POD_NUM_CONTAINERS
      value: "1"
    - name: FALCONCTL_OPTS
      value: --tags=VM,lab --cid=315CC7DD70854DE295D9CEFD0E6165B2-EC
    image: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor:6.31.0-1409.container.x86_64.Release.US-1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - bash
        - -c
        - '[[ "$(falconctl -g --aid)" =~ ^aid=\"[0-9a-f]+\"\.$ ]]'
      failureThreshold: 20
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: crowdstrike-falcon-container
    readinessProbe:
      exec:
        command:
        - bash
        - -c
        - '[[ "$(falconctl -g --aid)" =~ ^aid=\"[0-9a-f]+\"\.$ ]]'
      failureThreshold: 20
      initialDelaySeconds: 10
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/CrowdStrike
      name: crowdstrike-falcon-volume
    - mountPath: /etc/podinfo
      name: crowdstrike-falcon-podinfo
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-987l6
      readOnly: true
  - command:
    - /tmp/CrowdStrike/falcon-stub
    - --
    - /bin/sh
    - -c
    - while true;do echo 'hello there from pod';sleep 300;done
    image: busybox
    imagePullPolicy: Always
    name: busy-hello
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-987l6
      readOnly: true
    - mountPath: /tmp/CrowdStrike
      name: crowdstrike-falcon-volume
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: crowdstrike-falcon-pull-secret
  initContainers:
  - args:
    - /usr/bin/falcon-stub
    - /tmp/CrowdStrike/
    command:
    - /bin/cp
    image: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor:6.31.0-1409.container.x86_64.Release.US-1
    imagePullPolicy: IfNotPresent
    name: crowdstrike-falcon-init-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/CrowdStrike
      name: crowdstrike-falcon-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-987l6
      readOnly: true
  nodeName: rocky.adrian
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-987l6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - emptyDir: {}
    name: crowdstrike-falcon-volume
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: crowdstrike-falcon-podinfo
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-06T20:34:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-16T21:11:03Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-16T21:11:03Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-19T02:55:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://53db348d7279605d8f6c16b59bde44c78e1a55c1990ed62a73b211fe4d899bc7
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:b5cfd4befc119a590ca1a81d6bb0fa1fb19f1fbebd0397f25fae164abe1e8a6a
    lastState:
      terminated:
        containerID: containerd://24b9c81b0f98d1f10183983e01960e6a5ba1c70e2cf93b9cf6a64e387a3a7531
        exitCode: 143
        finishedAt: "2021-12-16T20:51:58Z"
        reason: Error
        startedAt: "2021-12-16T20:38:24Z"
    name: busy-hello
    ready: true
    restartCount: 7
    started: true
    state:
      running:
        startedAt: "2021-12-16T21:03:00Z"
  - containerID: containerd://b813b7e9825b4897f967b1421705603834809b2cc513483c0be365e58b6189ec
    image: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor:6.31.0-1409.container.x86_64.Release.US-1
    imageID: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor@sha256:487dd2a22cdff3b492543dc7dff2fd1c01c183cf81a5f041029a0853c775d337
    lastState:
      terminated:
        containerID: containerd://21cab9867f67afd087db719f8f855ae49e3501f4b2d51b04ed3eb1bbdf828371
        exitCode: 255
        finishedAt: "2021-12-16T20:59:39Z"
        reason: Unknown
        startedAt: "2021-12-16T20:52:17Z"
    name: crowdstrike-falcon-container
    ready: true
    restartCount: 8
    started: true
    state:
      running:
        startedAt: "2021-12-16T21:02:52Z"
  hostIP: 192.168.7.208
  initContainerStatuses:
  - containerID: containerd://d49893e7d7d7167b8c0a4eb52628074323e3381f1fc55b8eacc0db3b786e18f6
    image: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor:6.31.0-1409.container.x86_64.Release.US-1
    imageID: registry.crowdstrike.com/falcon-container/us-1/release/falcon-sensor@sha256:487dd2a22cdff3b492543dc7dff2fd1c01c183cf81a5f041029a0853c775d337
    lastState: {}
    name: crowdstrike-falcon-init-container
    ready: true
    restartCount: 7
    state:
      terminated:
        containerID: containerd://d49893e7d7d7167b8c0a4eb52628074323e3381f1fc55b8eacc0db3b786e18f6
        exitCode: 0
        finishedAt: "2021-12-16T21:02:47Z"
        reason: Completed
        startedAt: "2021-12-16T21:02:47Z"
  phase: Running
  podIP: 10.1.53.38
  podIPs:
  - ip: 10.1.53.38
  qosClass: BestEffort
  startTime: "2021-11-19T02:55:22Z"
